# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "GSoC: PGP-encrypted lists"
author: Jonax
email: "jonax at openmailbox dot org"
description: > # this means to ignore newlines until "baseurl:"
  This will serve as my GSoC 2016 project blog if my proposal gets accepted.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://cryptolists.github.io"
github_username:  cryptolists
gitlab_username: jonax
timezone: UTC
encoding: utf-8

# Build settings
markdown: kramdown

# Plugins
gems:
   - jekyll-feed
